# Generated by Django 5.2.6 on 2025-09-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('wishlist', 'Wishlist'), ('watching', 'Watching'), ('completed', 'Completed')], default='wishlist', max_length=20)),
                ('is_tv', models.BooleanField(default=False)),
                ('total_episodes', models.IntegerField(default=0)),
                ('episodes_watched', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('review', models.TextField(blank=True)),
            ],
        ),
    ]
