# Generated by Django 5.2.6 on 2025-09-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_movie_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer',
        ),
    ]
